kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "simple-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "simple-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.imageRepositoryName }}:{{ .Values.imageRepositoryTag }}"
          imagePullPolicy: {{ .Values.imageRepositoryPullPolicy }}
          ports:
            - containerPort: {{ .Values.servicePort }}
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: {{ .Values.servicePortName }}
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.serviceTargetPort }}
      protocol: TCP
  selector: {{- include "simple-app.selectorLabels" . | nindent 4 }}
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
spec:
  host: {{ .Values.deploymentName }}-{{ .Release.Namespace}}.{{ .Values.clusterAPI }}
  path: /
  to:
    kind: Service
    name: {{ .Values.serviceName }}
    weight: {{ .Values.serviceWeight }}
  port:
    targetPort: {{ .Values.servicePortName }}
  tls:
    termination:  {{ .Values.routeTermination }}
  wildcardPolicy: None
