apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .values.NameAndEnv }}
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: ocm-placement-generator
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: {{ .values.NameAndEnv }}-placement
  template:
    metadata:
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: '{{ "{{" }} name {{ "}}" }}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
        argocd.argoproj.io/skip-reconcile: "true" 
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true" 
      name: {{ .values.NameAndEnv }}
    spec:
      destination:
        namespace: {{ .values.NameAndEnv }}
        server: '{{ "{{" }} server {{ "}}" }}'
      project: {{ .Values.name }}
      source:
        repoURL: {{ .Values.configRepositoryURL }}
        path: {{ .Values.configRepositoryPath }}
        targetRevision: {{ .Values.configRepositoryRevision }}
        helm:
          releaseName: {{ .Values.helmReleaseName }}
          valueFiles:
          - {{ .Values.valuesFileName }}
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5 
          backoff:
            duration: 5s
            factor: 2 
            maxDuration: 30s