apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: {{ .Values.targetClusterSet }}
  namespace: {{ .Values.name }}-{{ .Values.environmentName }}
spec:
  clusterSet: {{ .Values.targetClusterSet }}