apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ .Values.name }}-{{ .Values.environmentName }}-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - {{ .Values.targetClusterSet }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            vendor: OpenShift