kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.pacman.deploymentName }}
  namespace: {{ .Values.pacman.namespace }}
  labels:
    {{- include "pacman.labels" . | nindent 4 }}
spec:
  host: {{ .Values.pacman.deploymentName }}-{{ .Release.Namespace}}.{{ .Values.pacman.clusterAPI }}
  path: /
  to:
    kind: Service
    name: {{ .Values.pacman.serviceName }}
    weight: {{ .Values.pacman.serviceWeight }}
  port:
    targetPort: {{ .Values.pacman.servicePortName }}
  tls:
    termination:  {{ .Values.pacman.routeTermination }}
  wildcardPolicy: None