kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pacman.labels" . | nindent 4 }}
spec:
  host: {{ .Values.deploymentName }}-{{ .Release.Namespace}}.{{ .Values.clusterAPI }}
  to:
    kind: Service
    name: {{ .Values.service.name }}
    weight: {{ .Values.service.weight }}
  port:
    targetPort: {{ .Values.service.portName }}