apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels: 
    {{- include "pacman.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: {{ .Values.servicePortName }}
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.serviceTargetPort }}
      protocol: TCP
  selector: {{- include "pacman.selectorLabels" . | nindent 4 }}