apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman-app-of-apps
  namespace: openshift-gitops
spec:
  destination:
    namespace: pacman-helm-dev
    server: https://kubernetes.default.svc
  source:
    path: ArgoCD/app-definitions
    
    repoURL: https://github.com/marrober/helm-charts.git
    targetRevision: HEAD
    directory: {}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true