apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman-app-of-apps
  namespace: openshift-gitops
spec:
  destination:
    namespace: pacman-helm-development
    server: https://kubernetes.default.svc
  source:
    path: ArgoCD/deployment/apps
    repoURL: https://github.com/marrober/helm-charts.git
    targetRevision: test-part-1
    directory: {}
  project: helm-argo-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:  
    - Validate=true 
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground 
    - PruneLast=true 
    retry:
      limit: 1 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 20s