apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman-app-of-apps-3
  namespace: openshift-gitops
spec:
  destination:
    namespace: pacman-helm-development-3
    server: https://kubernetes.default.svc
  source:
    path: ArgoCD-2/deployment/apps
    repoURL: https://github.com/marrober/helm-charts.git
    targetRevision: test-branch
    directory: {}
  project: helm-argo-3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:  
    - Validate=true 
    - CreateNamespace=true 
    - PrunePropagationPolicy=foreground 
    - PruneLast=true 
    retry:
      limit: 1 
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 20s